In [1]:
import numpy as np

In [2]:
def rnd_stochastic_matrix(rows=6, cols=6):
    '''
    The sum of each row equals to 1.0
    '''
    mat = np.random.rand(rows, cols)
    
    d = np.diag(np.sum(mat, axis=1))
    d_inv = np.linalg.inv(d)
    
    return np.matmul(d_inv, mat)

In [3]:
mat = rnd_stochastic_matrix()
mat

array([[0.047682  , 0.35379221, 0.03198258, 0.09868565, 0.17938772,
        0.28846984],
       [0.08331928, 0.09794226, 0.11229339, 0.24693897, 0.24330942,
        0.21619668],
       [0.10735769, 0.091517  , 0.16964969, 0.21589715, 0.34276155,
        0.07281693],
       [0.09689984, 0.21769726, 0.15589551, 0.22584087, 0.04565322,
        0.25801331],
       [0.02073023, 0.17273324, 0.16090135, 0.14008035, 0.19410914,
        0.31144568],
       [0.26311293, 0.2819172 , 0.04584441, 0.18699847, 0.03872045,
        0.18340655]])

In [9]:
eig = np.linalg.eig(mat)

In [10]:
eig.eigenvalues

array([ 1.        +0.j        , -0.19587185+0.j        ,
       -0.07610412+0.12350006j, -0.07610412-0.12350006j,
        0.17730299+0.j        ,  0.0894076 +0.j        ])

In [11]:
eig.eigenvectors

array([[ 0.40824829+0.j        , -0.43637637+0.j        ,
         0.37142171+0.04612344j,  0.37142171-0.04612344j,
        -0.32375941+0.j        ,  0.5229785 +0.j        ],
       [ 0.40824829+0.j        ,  0.43467614+0.j        ,
         0.02481156+0.42670367j,  0.02481156-0.42670367j,
         0.1151909 +0.j        , -0.16927463+0.j        ],
       [ 0.40824829+0.j        ,  0.5663551 +0.j        ,
         0.47902085+0.j        ,  0.47902085-0.j        ,
         0.78466134+0.j        , -0.18142144+0.j        ],
       [ 0.40824829+0.j        , -0.37507839+0.j        ,
        -0.32459493-0.07551821j, -0.32459493+0.07551821j,
         0.07555409+0.j        , -0.676234  +0.j        ],
       [ 0.40824829+0.j        , -0.37565106+0.j        ,
        -0.26471393+0.19345593j, -0.26471393-0.19345593j,
         0.14457056+0.j        ,  0.27216894+0.j        ],
       [ 0.40824829+0.j        ,  0.13444961+0.j        ,
         0.01299175-0.47857457j,  0.01299175+0.47857457j,
        -